### ISSUE TITLE
Error when running ./build.sh 0.10.0: "make: *** [build-stamp] Error 2"

### ISSUE THREAD

**Issue by kiranos** [mark-webster/node-debian#2]
This is what I get:
...
snapshot.a -Wl,--end-group -lm -ldl -lrt
  LINK(target) /root/node-debian/nodejs-0.10.0/out/Release/node: Finished
make[2]: Leaving directory `/root/node-debian/nodejs-0.10.0/out'
ln -fs out/Release/node node
make[1]: Leaving directory`/root/node-debian/nodejs-0.10.0'
make: **\* [build-stamp] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by mark-webster** [comment]
Could you paste the error from the build? That final error status doesn't contain any useful info.

**Comment by mark-webster** [comment]
(Also I should point out that any build errors are almost certainly to do with the nodejs sources - try building those separately and see if you get the same error)

**Comment by kiranos** [comment]
-lrt
  LINK(target) /root/node-debian/node-v0.10.0/out/Release/node: Finished
  touch /root/node-debian/node-v0.10.0/out/Release/obj.target/node_dtrace_header.stamp
  touch /root/node-debian/node-v0.10.0/out/Release/obj.target/node_dtrace_provider.stamp
  touch /root/node-debian/node-v0.10.0/out/Release/obj.target/node_dtrace_ustack.stamp
  touch /root/node-debian/node-v0.10.0/out/Release/obj.target/node_etw.stamp
  touch /root/node-debian/node-v0.10.0/out/Release/obj.target/node_perfctr.stamp
  touch /root/node-debian/node-v0.10.0/out/Release/obj.target/node_systemtap_header.stamp
make[1]: Leaving directory `/root/node-debian/node-v0.10.0/out'
ln -fs out/Release/node node

Is the last I get when compileing the soruce and that is without error, after that deb specific options kick in as seen above:

make: **\* [build-stamp] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

and that debian/rules build-stamp seems to come from.

/nodejs-0.10.0/debian/rules and in there somewher lies the problem?

**Comment by mark-webster** [comment]
If it's failing in the [build-stamp] target, then it's failing during building the sources. I don't think I can help you. Maybe check your file permissions?

Or try building 0.8.22?

**Comment by kiranos** [comment]
Hi I tried that its weird, but here is my build log (as far up I could reach now)
http://pastebin.com/nkuUJL45

If you can see anything, building from source with make seems to go without any errors.

**Comment by mark-webster** [comment]
Are you running out of space in /root ?

**Comment by mark-webster** [comment]
Pretty sure the error is happening when creating the symlink, one of the vanilla node.js build steps:
ln -fs out/Release/node node

This is really nothing to do with building the Debian packages, but something about your environment. Try building it in /usr/src/ and make sure you're not running out of space or something like that.

**Comment by kiranos** [comment]
I will test tomorrow but the space is not a problem. Will check more about the symlink

**Comment by kiranos** [comment]
sorry couldnt get it to work, compiling directyl went fine withiout issues, I ended up using fpm for building the deb package, I dont know what to look for here.

**Comment by mark-webster** [comment]
If you feel like doing one more test, you could remove the "-j6" option in debian/rules build-stamp - maybe your version of make isn't handling concurrency correctly? It will compile a lot slower, but maybe that's where the problem is happening?

**Comment by JanSchnacki** [comment]
I have the same error as kiranos. I've tried this:
- ./build.sh -> will fail, end of log: http://pastebin.com/vK6duQVP
- ./configure; make -> will work didn't try "make install" yet
- checkinstall -> will "work" but only installs the documentation

**Comment by mark-webster** [comment]
Ok, I'd like to get this fixed! Could you give me some system details? What version of Debian/Ubuntu?

**Comment by kiranos** [comment]
tomorrow I'll have time to remove -j6 and see if that fixes my issue, will report back then. I'm using Debian 6 (squeeze)

**Comment by JanSchnacki** [comment]
Ok, here's my setup:
- Debian 6.0.7
- put node-debian into /usr/src/node-debian/

What I tried:
- compile with ./build.sh per defaults
- compile without "-j6" from /usr/src/node-debian/deb/rules from the build-stamp section
- compile with ./configure and make
- compile with checkinstall

All but the "./configure; make" failed in some way or other.

**Comment by kiranos** [comment]
same error even without "-j6" I installed a new minimal vps of latest debian stable, ran:

apt-get install devscripts debhelper dpkg-dev make g++ cdbs dh-buildinfo openssl pkg-config build-essential curl zlib1g-dev git-core

git clone https://github.com/mark-webster/node-debian.git
./build.sh 0.10.0 (after edit of -j6)

**Comment by mark-webster** [comment]
Ok, I've got a completely virgin Debian Squeeze install, and I found this during the build logs:

<pre>cc1plus: warnings being treated as errors
../deps/v8/src/accessors.cc: In static member function ‘static v8::internal::MaybeObject* v8::internal::Accessors::FunctionGetCaller(v8::internal::Object*, void*)’:
../deps/v8/src/accessors.cc:714: error: ‘no_alloc.v8::internal::AssertNoAllocation::old_state_’ may be used uninitialized in this function</pre>

For some reason the Debian build adds the highlighted flags to the build command for <i>accessors.cc</i>:

<pre>g++ '-DENABLE_DEBUGGER_SUPPORT' '-DENABLE_EXTRA_CHECKS' '-DV8_TARGET_ARCH_IA32' '-DDEBUG' '-D_DEBUG' '-DENABLE_DISASSEMBLER' '-DV8_ENABLE_CHECKS' '-DOBJECT_PRINT' '-DVERIFY_HEAP' -I../deps/v8/src  -Wall -Wextra -Wno-unused-parameter -pthread -m32 -fno-strict-aliasing -m32 -g -O0 -Wall -Werror -W -Wno-unused-parameter -Wnon-virtual-dtor -Woverloaded-virtual -fno-rtti -fno-exceptions -MMD -MF /usr/src/node-debian/nodejs-0.10.0/out/Debug/.deps//usr/src/node-debian/nodejs-0.10.0/out/Debug/obj.target/v8_base/deps/v8/src/accessors.o.d.raw <b><u>-g -O2</u></b> -c -o /usr/src/node-debian/nodejs-0.10.0/out/Debug/obj.target/v8_base/deps/v8/src/accessors.o ../deps/v8/src/accessors.cc</pre>

This only happens when building <i>node_g</i>, so I've simply removed this from the build targets. Most people probably don't need this anyway.

If someone wants to help me understand why this is happening, please don't hesitate!

**Comment by ccoVeille** [comment]
Thanks a lot, it fixed my issue.
